apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "churn-predictor"
  namespace: "churn-model"
spec:
  predictor:
    serviceAccountName: sa-s3-access
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://churn-model-demo-cicd-hp/models/churn_model.pkl
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"